/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleBuilderRouteImport } from './routes/schedule-builder'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailyBriefingRouteImport } from './routes/daily-briefing'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AdminSeedRouteImport } from './routes/admin-seed'
import { Route as AdminDirectoryRouteImport } from './routes/admin-directory'
import { Route as ActiveJobsRouteImport } from './routes/active-jobs'
import { Route as AcknowledgementsRouteImport } from './routes/acknowledgements'
import { Route as AcknowledgeRouteImport } from './routes/acknowledge'
import { Route as IndexRouteImport } from './routes/index'

const ScheduleBuilderRoute = ScheduleBuilderRouteImport.update({
  id: '/schedule-builder',
  path: '/schedule-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyBriefingRoute = DailyBriefingRouteImport.update({
  id: '/daily-briefing',
  path: '/daily-briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeedRoute = AdminSeedRouteImport.update({
  id: '/admin-seed',
  path: '/admin-seed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDirectoryRoute = AdminDirectoryRouteImport.update({
  id: '/admin-directory',
  path: '/admin-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveJobsRoute = ActiveJobsRouteImport.update({
  id: '/active-jobs',
  path: '/active-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AcknowledgementsRoute = AcknowledgementsRouteImport.update({
  id: '/acknowledgements',
  path: '/acknowledgements',
  getParentRoute: () => rootRouteImport,
} as any)
const AcknowledgeRoute = AcknowledgeRouteImport.update({
  id: '/acknowledge',
  path: '/acknowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acknowledge': typeof AcknowledgeRoute
  '/acknowledgements': typeof AcknowledgementsRoute
  '/active-jobs': typeof ActiveJobsRoute
  '/admin-directory': typeof AdminDirectoryRoute
  '/admin-seed': typeof AdminSeedRoute
  '/contacts': typeof ContactsRoute
  '/daily-briefing': typeof DailyBriefingRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/schedule-builder': typeof ScheduleBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acknowledge': typeof AcknowledgeRoute
  '/acknowledgements': typeof AcknowledgementsRoute
  '/active-jobs': typeof ActiveJobsRoute
  '/admin-directory': typeof AdminDirectoryRoute
  '/admin-seed': typeof AdminSeedRoute
  '/contacts': typeof ContactsRoute
  '/daily-briefing': typeof DailyBriefingRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/schedule-builder': typeof ScheduleBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acknowledge': typeof AcknowledgeRoute
  '/acknowledgements': typeof AcknowledgementsRoute
  '/active-jobs': typeof ActiveJobsRoute
  '/admin-directory': typeof AdminDirectoryRoute
  '/admin-seed': typeof AdminSeedRoute
  '/contacts': typeof ContactsRoute
  '/daily-briefing': typeof DailyBriefingRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/schedule-builder': typeof ScheduleBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acknowledge'
    | '/acknowledgements'
    | '/active-jobs'
    | '/admin-directory'
    | '/admin-seed'
    | '/contacts'
    | '/daily-briefing'
    | '/dashboard'
    | '/documents'
    | '/help'
    | '/login'
    | '/profile'
    | '/reports'
    | '/schedule'
    | '/schedule-builder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acknowledge'
    | '/acknowledgements'
    | '/active-jobs'
    | '/admin-directory'
    | '/admin-seed'
    | '/contacts'
    | '/daily-briefing'
    | '/dashboard'
    | '/documents'
    | '/help'
    | '/login'
    | '/profile'
    | '/reports'
    | '/schedule'
    | '/schedule-builder'
  id:
    | '__root__'
    | '/'
    | '/acknowledge'
    | '/acknowledgements'
    | '/active-jobs'
    | '/admin-directory'
    | '/admin-seed'
    | '/contacts'
    | '/daily-briefing'
    | '/dashboard'
    | '/documents'
    | '/help'
    | '/login'
    | '/profile'
    | '/reports'
    | '/schedule'
    | '/schedule-builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcknowledgeRoute: typeof AcknowledgeRoute
  AcknowledgementsRoute: typeof AcknowledgementsRoute
  ActiveJobsRoute: typeof ActiveJobsRoute
  AdminDirectoryRoute: typeof AdminDirectoryRoute
  AdminSeedRoute: typeof AdminSeedRoute
  ContactsRoute: typeof ContactsRoute
  DailyBriefingRoute: typeof DailyBriefingRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ScheduleRoute: typeof ScheduleRoute
  ScheduleBuilderRoute: typeof ScheduleBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule-builder': {
      id: '/schedule-builder'
      path: '/schedule-builder'
      fullPath: '/schedule-builder'
      preLoaderRoute: typeof ScheduleBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-briefing': {
      id: '/daily-briefing'
      path: '/daily-briefing'
      fullPath: '/daily-briefing'
      preLoaderRoute: typeof DailyBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-seed': {
      id: '/admin-seed'
      path: '/admin-seed'
      fullPath: '/admin-seed'
      preLoaderRoute: typeof AdminSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-directory': {
      id: '/admin-directory'
      path: '/admin-directory'
      fullPath: '/admin-directory'
      preLoaderRoute: typeof AdminDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-jobs': {
      id: '/active-jobs'
      path: '/active-jobs'
      fullPath: '/active-jobs'
      preLoaderRoute: typeof ActiveJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acknowledgements': {
      id: '/acknowledgements'
      path: '/acknowledgements'
      fullPath: '/acknowledgements'
      preLoaderRoute: typeof AcknowledgementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acknowledge': {
      id: '/acknowledge'
      path: '/acknowledge'
      fullPath: '/acknowledge'
      preLoaderRoute: typeof AcknowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcknowledgeRoute: AcknowledgeRoute,
  AcknowledgementsRoute: AcknowledgementsRoute,
  ActiveJobsRoute: ActiveJobsRoute,
  AdminDirectoryRoute: AdminDirectoryRoute,
  AdminSeedRoute: AdminSeedRoute,
  ContactsRoute: ContactsRoute,
  DailyBriefingRoute: DailyBriefingRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ScheduleRoute: ScheduleRoute,
  ScheduleBuilderRoute: ScheduleBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
